# Generated by Django 3.1.7 on 2021-03-05 00:39

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("keywords", models.CharField(blank=True, max_length=120)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "updated",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                (
                    "created",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                ("publish_date", models.DateField(blank=True, null=True)),
            ],
            options={"ordering": ["publish_date"]},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.page",
                    ),
                )
            ],
            bases=("blog.page",),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.page",
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[(1, "Draft"), (2, "Published"), (3, "Delted")],
                        default=1,
                    ),
                ),
                (
                    "visibility",
                    models.IntegerField(
                        choices=[(1, "Public"), (2, "Internal"), (3, "Private")],
                        default=1,
                    ),
                ),
                ("preview", models.TextField(default="Preview", max_length=512)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="posts/thumbnails"),
                ),
                ("banner", models.ImageField(blank=True, upload_to="posts/banner")),
                (
                    "post_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.category",
                    ),
                ),
                ("tags", models.ManyToManyField(to="blog.Tag")),
            ],
            bases=("blog.page",),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.SmallIntegerField()),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Text"),
                            (2, "Image"),
                            (3, "Image Left"),
                            (4, "Image Right"),
                            (5, "Video"),
                            (6, "Video Left"),
                            (7, "Video Right"),
                        ],
                        default=1,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="posts")),
                ("video", models.CharField(blank=True, max_length=255)),
                ("text", markdownx.models.MarkdownxField(blank=True, max_length=16384)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="blog.post",
                    ),
                ),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("post", "order"), name="post_sections"
            ),
        ),
    ]
