# Generated by Django 3.1.7 on 2021-03-12 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page", options={"ordering": ["-publish_date"]}
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "permissions": [
                    ("can_read_all_post", "Can read private posts"),
                    ("can_read_restricted_post", "Can read internal posts"),
                    ("can_create_post", "Can create posts as draft"),
                    ("can_delete-post", "Can delete posts in status draft"),
                    ("can_publish_post", "Can un/publish posts"),
                ]
            },
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="media_alt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="media_caption",
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="media_left",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="state",
            field=models.IntegerField(
                choices=[(1, "Draft"), (2, "Published"), (3, "Deleted")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="image",
            field=models.ImageField(null=True, upload_to="posts"),
        ),
        migrations.AlterField(
            model_name="section",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Text"),
                    (2, "Image"),
                    (3, "Video"),
                    (4, "Text Image"),
                    (5, "Text Video"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="video",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
